/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

/**
 *
 * @author mgsr1
 */
public class Interfaz extends javax.swing.JFrame {
    HashTable tabla = new HashTable(100);
    HashTable keys = new HashTable(60);
    ArbolAVL autores;
    ArbolAVL keywords;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.sel.setVisible(false);
        this.selbusq.setVisible(false);
        this.jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        aut = new javax.swing.JComboBox<>();
        exit = new javax.swing.JButton();
        cargarResu = new javax.swing.JButton();
        busqresu = new javax.swing.JButton();
        busqkeywinv = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        keyw = new javax.swing.JComboBox<>();
        busqaut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sel = new javax.swing.JComboBox<>();
        selbusq = new javax.swing.JButton();
        keywsee = new javax.swing.JButton();
        contses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel1.setText("Resumen a seleccionar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        getContentPane().add(resu, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 160, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 410, 300));

        jLabel2.setText("Búsqueda por autor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        getContentPane().add(aut, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 170, -1));

        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, -1));

        cargarResu.setText("Añadir resumen");
        cargarResu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarResuActionPerformed(evt);
            }
        });
        getContentPane().add(cargarResu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        busqresu.setText("Analizar");
        busqresu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqresuActionPerformed(evt);
            }
        });
        getContentPane().add(busqresu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        busqkeywinv.setText("Investigación");
        busqkeywinv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqkeywinvActionPerformed(evt);
            }
        });
        getContentPane().add(busqkeywinv, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jLabel3.setText("Búsqueda por palabra clave:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        getContentPane().add(keyw, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 130, -1));

        busqaut.setText("Continuar");
        busqaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqautActionPerformed(evt);
            }
        });
        getContentPane().add(busqaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jLabel4.setText("Selección:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        getContentPane().add(sel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        selbusq.setText("Continuar");
        selbusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selbusqActionPerformed(evt);
            }
        });
        getContentPane().add(selbusq, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        keywsee.setText("Ver palabra");
        keywsee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywseeActionPerformed(evt);
            }
        });
        getContentPane().add(keywsee, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        contses.setText("Continuar sesión previa");
        contses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contsesActionPerformed(evt);
            }
        });
        getContentPane().add(contses, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        ManejoArchivos archi = new ManejoArchivos();
        archi.actualizar_archivo(tabla);
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void cargarResuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarResuActionPerformed
        this.contses.setEnabled(false);
        ManejoArchivos archi = new ManejoArchivos();
        archi.subir_archivo(tabla);
        this.autores = this.tabla.creaArbolAutores();
        System.out.println("creo arbol autores");
        this.keywords = this.tabla.creaArbolKeywords();
        System.out.println("creo arbol keywords");
        System.out.println(this.autores.imprimirInOrden());
        String [] textoarbol = this.autores.imprimirInOrden().split(",");
        for(String s: textoarbol){
            this.aut.addItem(s);
        }
        String [] textokeywords = this.keywords.imprimirInOrden().split(",");
        for(String s2: textokeywords){
            this.keyw.addItem(s2);
        }
        String [] texto4 = this.tabla.MostrarTitulos().split(".");
        for(String s3: texto4){
            this.resu.addItem(s3);
        }
    }//GEN-LAST:event_cargarResuActionPerformed

    private void busqkeywinvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqkeywinvActionPerformed
        this.contses.setEnabled(false);
        Investigaciones [] aux =this.tabla.BuscarPalabraClave(this.keyw.getSelectedItem().toString());
        this.sel.setVisible(true);
        this.selbusq.setVisible(true);
        this.jLabel4.setVisible(true);
        String texto = "";
        for(Investigaciones aux2: aux){
            texto += aux2.titulo + "\n";
            this.sel.addItem(aux2.titulo);
        }
        this.jTextArea1.setText(texto);
    }//GEN-LAST:event_busqkeywinvActionPerformed

    private void busqautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqautActionPerformed
        this.contses.setEnabled(false);
        NodoArbol aux = this.autores.Buscar(this.autores.raiz, this.aut.getSelectedItem().toString());
        NodoInvestigacion aux2 = aux.lista.pfirst;
        this.sel.setVisible(true);
        this.selbusq.setVisible(true);
        this.jLabel4.setVisible(true);
        String texto = "";
        while(aux2 != null){
            texto += aux2.info +"\n";
            this.sel.addItem(aux2.info);
            aux2 = aux2.pnext;
        }
        this.jTextArea1.setText(texto);
    }//GEN-LAST:event_busqautActionPerformed

    private void busqresuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqresuActionPerformed
        this.contses.setEnabled(false);
        String texto = this.tabla.BuscarResumen(this.resu.getSelectedItem().toString()).mostrarcomp();
        this.jTextArea1.setText(texto);
    }//GEN-LAST:event_busqresuActionPerformed

    private void selbusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selbusqActionPerformed
        this.contses.setEnabled(false);
        String texto = this.sel.getSelectedItem().toString();
        this.jTextArea1.setText(this.tabla.BuscarResumen(texto).mostrarcomp());
    }//GEN-LAST:event_selbusqActionPerformed

    private void keywseeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywseeActionPerformed
        this.contses.setEnabled(false);
        NodoArbol aux = this.keywords.Buscar(this.keywords.raiz, this.keyw.getSelectedItem().toString());
        this.jTextArea1.setText(aux.lista.mostrarfreqkeyw(tabla, this.keyw.getSelectedItem().toString()));
    }//GEN-LAST:event_keywseeActionPerformed

    private void contsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contsesActionPerformed
        ManejoArchivos archi = new ManejoArchivos();
        archi.subir_archivocomp(tabla);
        this.autores = this.tabla.creaArbolAutores();
        this.keywords = this.tabla.creaArbolKeywords();
        String [] textoarbol = this.autores.imprimirInOrden().split(",");
        for(String s: textoarbol){
            this.aut.addItem(s);
        }
        String [] textokeywords = this.keywords.imprimirInOrden().split(",");
        for(String s2: textokeywords){
            this.keyw.addItem(s2);
        }
        String [] texto4 = this.tabla.MostrarTitulos().split(".");
        for(String s3: texto4){
            this.resu.addItem(s3);
        }
        this.contses.setEnabled(false);
    }//GEN-LAST:event_contsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aut;
    private javax.swing.JButton busqaut;
    private javax.swing.JButton busqkeywinv;
    private javax.swing.JButton busqresu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cargarResu;
    private javax.swing.JButton contses;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> keyw;
    private javax.swing.JButton keywsee;
    private javax.swing.JComboBox<String> resu;
    private javax.swing.JComboBox<String> sel;
    private javax.swing.JButton selbusq;
    // End of variables declaration//GEN-END:variables
}
